#!python3

import argparse
import sys
import os

# parse args
parser = argparse.ArgumentParser(description='Deploy CDN.')
parser.add_argument('-p')
parser.add_argument('-o')
parser.add_argument('-n')
parser.add_argument('-u')
parser.add_argument('-i')

args = parser.parse_args(sys.argv[1:])
port = int(args.p)
origin = args.o
name = args.n
username = args.u
keyfile = args.i


# upload local files to the directory of remote nodes
def upload(files, nodes):
    for node in nodes:
        node = node.strip()
        print(os.popen('scp -i {} {} {}@{}:~/\\'.format(keyfile, ' '.join(files), username, node)).read())

# run command on remote nodes
def run(nodes, command):
    for node in nodes:
        print(os.popen('ssh -i {} {}@{} \'{}\''.format(keyfile, username, node, command)).read())


# upload dns
with open('./dns_nodes', 'r') as f:
    nodes = f.readlines()
    run(nodes, 'rm -rf *')
    upload(['./__init__.py', './dnsserver', './mapping.py', './geo.py', './geo_db.csv'], nodes)

# upload http
with open('./replica_server', 'r') as f:
    upload(['./httpserver', './pageview.csv'], f.readlines(), 'p5')

# ./deployCDN -p 40007 -o cs5700cdnorigin.ccs.neu.edu -n <name> -u content_destroy_ninjas -i <keyfile>
