#!python3

import argparse
import sys
import os

# parse args
# ./deployCDN -p 40007 -o cs5700cdnorigin.ccs.neu.edu -n <name> -u content_destroy_ninjas -i <keyfile>
parser = argparse.ArgumentParser(description='Deploy CDN.')
parser.add_argument('-p')
parser.add_argument('-o')
parser.add_argument('-n')
parser.add_argument('-u')
parser.add_argument('-i')

args = parser.parse_args(sys.argv[1:])
port = int(args.p)
origin = args.o
name = args.n
username = args.u
keyfile = args.i


# upload local files to the directory of remote nodes
def upload(nodes, files):
    for node in nodes:
        print(os.popen('scp -i {} {} {}@{}:~/\\'.format(keyfile, ' '.join(files), username, node)).read())
        print('uploaded on {}'.format(node))
        print()

# run command on remote nodes
def run(nodes, command):
    for node in nodes:
        print(os.popen('ssh -i {} {}@{} \'{}\''.format(keyfile, username, node, command)).read())


# upload dns
with open('./dns_nodes', 'r') as f:
    nodes = [line for line in f.readlines() if len(line.strip()) != 0]
    run(nodes, 'rm -rf *')
    upload(nodes, ['./__init__.py', './dnsserver', './mapping.py', './geo.py', './geo_db.csv'])

# upload http
with open('./replica_server', 'r') as f:
    nodes = [line.strip() for line in f.readlines() if len(line) != 0]
    run(nodes, 'rm -rf *')
    upload(nodes, ['./__init__.py', './httpserver', './cache.py', './pageviews.csv'])

