#!python3

import argparse
import os
import sys
import time

# parse args
parser = argparse.ArgumentParser(description='Deploy CDN.')
parser.add_argument('-p')
parser.add_argument('-o')
parser.add_argument('-n')
parser.add_argument('-u')
parser.add_argument('-i')

args = parser.parse_args(sys.argv[1:])
port = int(args.p)
origin = args.o
name = args.n
username = args.u
keyfile = args.i


# run command on remote nodes
def run(nodes, command):
    for node in nodes:
        os.popen('ssh -i {} {}@{} \'{} &> /dev/null &\''.format(keyfile, username, node, command))
        print('started on node ' + node)
        print()


# run dns
print('start dns servers...')
with open('./dns_nodes', 'r') as f:
    nodes = [line.strip() for line in f.readlines() if len(line.strip()) != 0]
    run(nodes, 'python3 ./dnsserver {} {}'.format(port, name))


# run http
print('start http servers...')
with open('./replica_server', 'r') as f:
    nodes = [line.strip() for line in f.readlines() if len(line.strip()) != 0]
    run(nodes, 'python3 ./httpserver {} {}'.format(port, origin))

print('sleep 5 seconds for servers to intialize...')
time.sleep(5)
