#!python3

import argparse
import os
import sys

# parse args
parser = argparse.ArgumentParser(description='Deploy CDN.')
parser.add_argument('-p')
parser.add_argument('-o')
parser.add_argument('-n')
parser.add_argument('-u')
parser.add_argument('-i')

args = parser.parse_args(sys.argv[1:])
port = int(args.p)
origin = args.o
name = args.n
username = args.u
keyfile = args.i


# run command on remote nodes and return result
def run(node, command):
    return os.popen('ssh -i {} {}@{} \"{}\"'.format(keyfile, username, node, command)).read()


def stop(nodes):
    for node in nodes:
        out = run(node, 'lsof -i:{}'.format(port))
        if out == '':
            print('failed stop on node {}, cannot get pid on given port'.format(node))
            continue
        if 'Too many logins' in out:
            print('failed stop on node {}, too many logins'.format(node))
            continue

        run(node, 'kill ' + out.split('\n')[1].split(' ')[1])
        print('stopped on node ' + node)


# stop dns and https
print('stop dns servers...')
with open('./dns_nodes', 'r') as f:
    stop(f.readlines())

# stop http and https
print('stop http servers...')
with open('./replica_server', 'r') as f:
    stop(f.readlines())
